version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - fastapi

volumes:
  caddy_data:
  caddy_config: