version: '3.8'

services:
  fastapi:
    build: .
    container_name: computeragent-pro
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - .env
    ports:
      - "0.0.0.0:8000:8000"
